//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test_project.MailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:MailService", ConfigurationName="MailService.MailServicePortType")]
    public interface MailServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/addContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string addContact([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, string email, string domain, long mtype, string fullname, string mobile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/add_list", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string add_list([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, string domain, [System.ServiceModel.MessageParameterAttribute(Name="contact-list")] [System.Xml.Serialization.SoapElementAttribute("contact-list")] string[] contactlist, long mtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/fr_sendMails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string fr_sendMails(string domain, [System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, [System.ServiceModel.MessageParameterAttribute(Name="from-email")] [System.Xml.Serialization.SoapElementAttribute("from-email")] string fromemail, string subject, string content, string mtype, [System.ServiceModel.MessageParameterAttribute(Name="start-time")] [System.Xml.Serialization.SoapElementAttribute("start-time")] string starttime, [System.ServiceModel.MessageParameterAttribute(Name="from-name")] [System.Xml.Serialization.SoapElementAttribute("from-name")] string fromname, [System.ServiceModel.MessageParameterAttribute(Name="reply-to")] [System.Xml.Serialization.SoapElementAttribute("reply-to")] string replyto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/fr_send_mails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string fr_send_mails(string domain, [System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, [System.ServiceModel.MessageParameterAttribute(Name="from-email")] [System.Xml.Serialization.SoapElementAttribute("from-email")] string fromemail, string subject, string content, string maillist, [System.ServiceModel.MessageParameterAttribute(Name="from-name")] [System.Xml.Serialization.SoapElementAttribute("from-name")] string fromname, [System.ServiceModel.MessageParameterAttribute(Name="reply-to")] [System.Xml.Serialization.SoapElementAttribute("reply-to")] string replyto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/getLists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string getLists([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/getMobileOfList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string getMobileOfList([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, string domain, [System.ServiceModel.MessageParameterAttribute(Name="list-name")] [System.Xml.Serialization.SoapElementAttribute("list-name")] string listname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/getNumberOfList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string getNumberOfList([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, string domain, [System.ServiceModel.MessageParameterAttribute(Name="list-name")] [System.Xml.Serialization.SoapElementAttribute("list-name")] string listname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/getStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string getStatus([System.ServiceModel.MessageParameterAttribute(Name="job-id")] [System.Xml.Serialization.SoapElementAttribute("job-id")] string jobid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/mc_sendmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string mc_sendmail([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, string[] parameters, string template);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/removeContact", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string removeContact([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, string email, string domain, string mtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/remove_list", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string remove_list([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, string domain, long mtype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/sendMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string sendMail([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, [System.ServiceModel.MessageParameterAttribute(Name="from-email")] [System.Xml.Serialization.SoapElementAttribute("from-email")] string fromemail, string subject, string content, [System.ServiceModel.MessageParameterAttribute(Name="to-email")] [System.Xml.Serialization.SoapElementAttribute("to-email")] string toemail, [System.ServiceModel.MessageParameterAttribute(Name="from-name")] [System.Xml.Serialization.SoapElementAttribute("from-name")] string fromname, string cc, string bcc, [System.ServiceModel.MessageParameterAttribute(Name="reply-to")] [System.Xml.Serialization.SoapElementAttribute("reply-to")] string replyto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/sendMails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string sendMails([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, [System.ServiceModel.MessageParameterAttribute(Name="from-email")] [System.Xml.Serialization.SoapElementAttribute("from-email")] string fromemail, string subject, string content, string mtype, [System.ServiceModel.MessageParameterAttribute(Name="start-time")] [System.Xml.Serialization.SoapElementAttribute("start-time")] string starttime, [System.ServiceModel.MessageParameterAttribute(Name="from-name")] [System.Xml.Serialization.SoapElementAttribute("from-name")] string fromname, [System.ServiceModel.MessageParameterAttribute(Name="reply-to")] [System.Xml.Serialization.SoapElementAttribute("reply-to")] string replyto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/send_mail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string send_mail([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, string domain, [System.ServiceModel.MessageParameterAttribute(Name="from-email")] [System.Xml.Serialization.SoapElementAttribute("from-email")] string fromemail, string subject, string content, [System.ServiceModel.MessageParameterAttribute(Name="to-email")] [System.Xml.Serialization.SoapElementAttribute("to-email")] string toemail, [System.ServiceModel.MessageParameterAttribute(Name="from-name")] [System.Xml.Serialization.SoapElementAttribute("from-name")] string fromname, string cc, string bcc, [System.ServiceModel.MessageParameterAttribute(Name="reply-to")] [System.Xml.Serialization.SoapElementAttribute("reply-to")] string replyto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/send_mails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string send_mails([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, [System.ServiceModel.MessageParameterAttribute(Name="from-email")] [System.Xml.Serialization.SoapElementAttribute("from-email")] string fromemail, string subject, string content, string maillist, [System.ServiceModel.MessageParameterAttribute(Name="from-name")] [System.Xml.Serialization.SoapElementAttribute("from-name")] string fromname, [System.ServiceModel.MessageParameterAttribute(Name="reply-to")] [System.Xml.Serialization.SoapElementAttribute("reply-to")] string replyto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/send_special_mail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string send_special_mail([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, [System.ServiceModel.MessageParameterAttribute(Name="from-email")] [System.Xml.Serialization.SoapElementAttribute("from-email")] string fromemail, string subject, string content, [System.ServiceModel.MessageParameterAttribute(Name="to-email")] [System.Xml.Serialization.SoapElementAttribute("to-email")] string toemail, [System.ServiceModel.MessageParameterAttribute(Name="from-name")] [System.Xml.Serialization.SoapElementAttribute("from-name")] string fromname, string cc, string bcc, [System.ServiceModel.MessageParameterAttribute(Name="reply-to")] [System.Xml.Serialization.SoapElementAttribute("reply-to")] string replyto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/st_send_mail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string st_send_mail([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, [System.ServiceModel.MessageParameterAttribute(Name="from-name")] [System.Xml.Serialization.SoapElementAttribute("from-name")] string fromname, [System.ServiceModel.MessageParameterAttribute(Name="from-email")] [System.Xml.Serialization.SoapElementAttribute("from-email")] string fromemail, string subject, string content, [System.ServiceModel.MessageParameterAttribute(Name="to-email")] [System.Xml.Serialization.SoapElementAttribute("to-email")] string toemail, [System.ServiceModel.MessageParameterAttribute(Name="reply-to")] [System.Xml.Serialization.SoapElementAttribute("reply-to")] string replyto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.sting.todo.vn:28110/MailService/soap/stop_job", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="result")]
        string stop_job([System.ServiceModel.MessageParameterAttribute(Name="secure-key")] [System.Xml.Serialization.SoapElementAttribute("secure-key")] string securekey, string domain, [System.ServiceModel.MessageParameterAttribute(Name="job-id")] [System.Xml.Serialization.SoapElementAttribute("job-id")] string jobid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailServicePortTypeChannel : test_project.MailService.MailServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailServicePortTypeClient : System.ServiceModel.ClientBase<test_project.MailService.MailServicePortType>, test_project.MailService.MailServicePortType {
        
        public MailServicePortTypeClient() {
        }
        
        public MailServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addContact(string securekey, string email, string domain, long mtype, string fullname, string mobile) {
            return base.Channel.addContact(securekey, email, domain, mtype, fullname, mobile);
        }
        
        public string add_list(string securekey, string domain, string[] contactlist, long mtype) {
            return base.Channel.add_list(securekey, domain, contactlist, mtype);
        }
        
        public string fr_sendMails(string domain, string securekey, string fromemail, string subject, string content, string mtype, string starttime, string fromname, string replyto) {
            return base.Channel.fr_sendMails(domain, securekey, fromemail, subject, content, mtype, starttime, fromname, replyto);
        }
        
        public string fr_send_mails(string domain, string securekey, string fromemail, string subject, string content, string maillist, string fromname, string replyto) {
            return base.Channel.fr_send_mails(domain, securekey, fromemail, subject, content, maillist, fromname, replyto);
        }
        
        public string getLists(string securekey, string domain) {
            return base.Channel.getLists(securekey, domain);
        }
        
        public string getMobileOfList(string securekey, string domain, string listname) {
            return base.Channel.getMobileOfList(securekey, domain, listname);
        }
        
        public string getNumberOfList(string securekey, string domain, string listname) {
            return base.Channel.getNumberOfList(securekey, domain, listname);
        }
        
        public string getStatus(string jobid) {
            return base.Channel.getStatus(jobid);
        }
        
        public string mc_sendmail(string securekey, string[] parameters, string template) {
            return base.Channel.mc_sendmail(securekey, parameters, template);
        }
        
        public string removeContact(string securekey, string email, string domain, string mtype) {
            return base.Channel.removeContact(securekey, email, domain, mtype);
        }
        
        public string remove_list(string securekey, string domain, long mtype) {
            return base.Channel.remove_list(securekey, domain, mtype);
        }
        
        public string sendMail(string securekey, string fromemail, string subject, string content, string toemail, string fromname, string cc, string bcc, string replyto) {
            return base.Channel.sendMail(securekey, fromemail, subject, content, toemail, fromname, cc, bcc, replyto);
        }
        
        public string sendMails(string securekey, string fromemail, string subject, string content, string mtype, string starttime, string fromname, string replyto) {
            return base.Channel.sendMails(securekey, fromemail, subject, content, mtype, starttime, fromname, replyto);
        }
        
        public string send_mail(string securekey, string domain, string fromemail, string subject, string content, string toemail, string fromname, string cc, string bcc, string replyto) {
            return base.Channel.send_mail(securekey, domain, fromemail, subject, content, toemail, fromname, cc, bcc, replyto);
        }
        
        public string send_mails(string securekey, string fromemail, string subject, string content, string maillist, string fromname, string replyto) {
            return base.Channel.send_mails(securekey, fromemail, subject, content, maillist, fromname, replyto);
        }
        
        public string send_special_mail(string securekey, string fromemail, string subject, string content, string toemail, string fromname, string cc, string bcc, string replyto) {
            return base.Channel.send_special_mail(securekey, fromemail, subject, content, toemail, fromname, cc, bcc, replyto);
        }
        
        public string st_send_mail(string securekey, string fromname, string fromemail, string subject, string content, string toemail, string replyto) {
            return base.Channel.st_send_mail(securekey, fromname, fromemail, subject, content, toemail, replyto);
        }
        
        public string stop_job(string securekey, string domain, string jobid) {
            return base.Channel.stop_job(securekey, domain, jobid);
        }
    }
}
