//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HS.Service.Connection.HSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DanhMucData", Namespace="http://schemas.datacontract.org/2004/07/HS.Server.Data.Entities.Systems")]
    [System.SerializableAttribute()]
    public partial class DanhMucData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> SystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenLoaiDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ThuTuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLoaiDanhMuc {
            get {
                return this.MaLoaiDanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiDanhMucField, value) != true)) {
                    this.MaLoaiDanhMucField = value;
                    this.RaisePropertyChanged("MaLoaiDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> System {
            get {
                return this.SystemField;
            }
            set {
                if ((this.SystemField.Equals(value) != true)) {
                    this.SystemField = value;
                    this.RaisePropertyChanged("System");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenLoaiDanhMuc {
            get {
                return this.TenLoaiDanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.TenLoaiDanhMucField, value) != true)) {
                    this.TenLoaiDanhMucField = value;
                    this.RaisePropertyChanged("TenLoaiDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ThuTu {
            get {
                return this.ThuTuField;
            }
            set {
                if ((this.ThuTuField.Equals(value) != true)) {
                    this.ThuTuField = value;
                    this.RaisePropertyChanged("ThuTu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DanhMucItemData", Namespace="http://schemas.datacontract.org/2004/07/HS.Server.Data.Entities.Systems")]
    [System.SerializableAttribute()]
    public partial class DanhMucItemData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DecVal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DecVal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DecVal3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IntVal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IntVal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IntVal3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaLoaiDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrVal1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrVal2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrVal3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ThuTuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DecVal1 {
            get {
                return this.DecVal1Field;
            }
            set {
                if ((this.DecVal1Field.Equals(value) != true)) {
                    this.DecVal1Field = value;
                    this.RaisePropertyChanged("DecVal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DecVal2 {
            get {
                return this.DecVal2Field;
            }
            set {
                if ((this.DecVal2Field.Equals(value) != true)) {
                    this.DecVal2Field = value;
                    this.RaisePropertyChanged("DecVal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> DecVal3 {
            get {
                return this.DecVal3Field;
            }
            set {
                if ((this.DecVal3Field.Equals(value) != true)) {
                    this.DecVal3Field = value;
                    this.RaisePropertyChanged("DecVal3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntVal1 {
            get {
                return this.IntVal1Field;
            }
            set {
                if ((this.IntVal1Field.Equals(value) != true)) {
                    this.IntVal1Field = value;
                    this.RaisePropertyChanged("IntVal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntVal2 {
            get {
                return this.IntVal2Field;
            }
            set {
                if ((this.IntVal2Field.Equals(value) != true)) {
                    this.IntVal2Field = value;
                    this.RaisePropertyChanged("IntVal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IntVal3 {
            get {
                return this.IntVal3Field;
            }
            set {
                if ((this.IntVal3Field.Equals(value) != true)) {
                    this.IntVal3Field = value;
                    this.RaisePropertyChanged("IntVal3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaDanhMuc {
            get {
                return this.MaDanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.MaDanhMucField, value) != true)) {
                    this.MaDanhMucField = value;
                    this.RaisePropertyChanged("MaDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaLoaiDanhMuc {
            get {
                return this.MaLoaiDanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.MaLoaiDanhMucField, value) != true)) {
                    this.MaLoaiDanhMucField = value;
                    this.RaisePropertyChanged("MaLoaiDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrVal1 {
            get {
                return this.StrVal1Field;
            }
            set {
                if ((object.ReferenceEquals(this.StrVal1Field, value) != true)) {
                    this.StrVal1Field = value;
                    this.RaisePropertyChanged("StrVal1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrVal2 {
            get {
                return this.StrVal2Field;
            }
            set {
                if ((object.ReferenceEquals(this.StrVal2Field, value) != true)) {
                    this.StrVal2Field = value;
                    this.RaisePropertyChanged("StrVal2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrVal3 {
            get {
                return this.StrVal3Field;
            }
            set {
                if ((object.ReferenceEquals(this.StrVal3Field, value) != true)) {
                    this.StrVal3Field = value;
                    this.RaisePropertyChanged("StrVal3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDanhMuc {
            get {
                return this.TenDanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDanhMucField, value) != true)) {
                    this.TenDanhMucField = value;
                    this.RaisePropertyChanged("TenDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ThuTu {
            get {
                return this.ThuTuField;
            }
            set {
                if ((this.ThuTuField.Equals(value) != true)) {
                    this.ThuTuField = value;
                    this.RaisePropertyChanged("ThuTu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HSService.ISystem")]
    public interface ISystem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucService/AddDanhMuc", ReplyAction="http://tempuri.org/IDanhMucService/AddDanhMucResponse")]
        int AddDanhMuc(HS.Service.Connection.HSService.DanhMucData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucService/ChangeDanhMuc", ReplyAction="http://tempuri.org/IDanhMucService/ChangeDanhMucResponse")]
        int ChangeDanhMuc(HS.Service.Connection.HSService.DanhMucData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucService/RemoveDanhMuc", ReplyAction="http://tempuri.org/IDanhMucService/RemoveDanhMucResponse")]
        int RemoveDanhMuc(HS.Service.Connection.HSService.DanhMucData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucService/GetDanhMucs", ReplyAction="http://tempuri.org/IDanhMucService/GetDanhMucsResponse")]
        System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucData> GetDanhMucs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucService/GetDanhMucByID", ReplyAction="http://tempuri.org/IDanhMucService/GetDanhMucByIDResponse")]
        HS.Service.Connection.HSService.DanhMucData GetDanhMucByID(string maLoaiDanhMuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucService/GetDanhMucByCriteria", ReplyAction="http://tempuri.org/IDanhMucService/GetDanhMucByCriteriaResponse")]
        System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucData> GetDanhMucByCriteria(string whereCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucService/GetDanhMucBySizeCriteria", ReplyAction="http://tempuri.org/IDanhMucService/GetDanhMucBySizeCriteriaResponse")]
        System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucData> GetDanhMucBySizeCriteria(int size, string whereCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucService/GetDanhMucCount", ReplyAction="http://tempuri.org/IDanhMucService/GetDanhMucCountResponse")]
        int GetDanhMucCount(string whereCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucService/GetDanhMucPaging", ReplyAction="http://tempuri.org/IDanhMucService/GetDanhMucPagingResponse")]
        System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucData> GetDanhMucPaging(string whereCondition, int pageSize, int currentPage, string sortByColumns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucItemService/AddDanhMucItem", ReplyAction="http://tempuri.org/IDanhMucItemService/AddDanhMucItemResponse")]
        int AddDanhMucItem(HS.Service.Connection.HSService.DanhMucItemData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucItemService/ChangeDanhMucItem", ReplyAction="http://tempuri.org/IDanhMucItemService/ChangeDanhMucItemResponse")]
        int ChangeDanhMucItem(HS.Service.Connection.HSService.DanhMucItemData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucItemService/RemoveDanhMucItem", ReplyAction="http://tempuri.org/IDanhMucItemService/RemoveDanhMucItemResponse")]
        int RemoveDanhMucItem(HS.Service.Connection.HSService.DanhMucItemData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucItemService/GetDanhMucItemsByDanhMuc", ReplyAction="http://tempuri.org/IDanhMucItemService/GetDanhMucItemsByDanhMucResponse")]
        System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucItemData> GetDanhMucItemsByDanhMuc(string maLoaiDanhMuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucItemService/GetDanhMucItems", ReplyAction="http://tempuri.org/IDanhMucItemService/GetDanhMucItemsResponse")]
        System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucItemData> GetDanhMucItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucItemService/GetDanhMucItemByID", ReplyAction="http://tempuri.org/IDanhMucItemService/GetDanhMucItemByIDResponse")]
        HS.Service.Connection.HSService.DanhMucItemData GetDanhMucItemByID(System.Guid iD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucItemService/GetDanhMucItemByCriteria", ReplyAction="http://tempuri.org/IDanhMucItemService/GetDanhMucItemByCriteriaResponse")]
        System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucItemData> GetDanhMucItemByCriteria(string whereCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucItemService/GetDanhMucItemBySizeCriteria", ReplyAction="http://tempuri.org/IDanhMucItemService/GetDanhMucItemBySizeCriteriaResponse")]
        System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucItemData> GetDanhMucItemBySizeCriteria(int size, string whereCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucItemService/GetDanhMucItemCount", ReplyAction="http://tempuri.org/IDanhMucItemService/GetDanhMucItemCountResponse")]
        int GetDanhMucItemCount(string whereCondition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDanhMucItemService/GetDanhMucItemPaging", ReplyAction="http://tempuri.org/IDanhMucItemService/GetDanhMucItemPagingResponse")]
        System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucItemData> GetDanhMucItemPaging(string whereCondition, int pageSize, int currentPage, string sortByColumns);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemChannel : HS.Service.Connection.HSService.ISystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemClient : System.ServiceModel.ClientBase<HS.Service.Connection.HSService.ISystem>, HS.Service.Connection.HSService.ISystem {
        
        public SystemClient() {
        }
        
        public SystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddDanhMuc(HS.Service.Connection.HSService.DanhMucData data) {
            return base.Channel.AddDanhMuc(data);
        }
        
        public int ChangeDanhMuc(HS.Service.Connection.HSService.DanhMucData data) {
            return base.Channel.ChangeDanhMuc(data);
        }
        
        public int RemoveDanhMuc(HS.Service.Connection.HSService.DanhMucData data) {
            return base.Channel.RemoveDanhMuc(data);
        }
        
        public System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucData> GetDanhMucs() {
            return base.Channel.GetDanhMucs();
        }
        
        public HS.Service.Connection.HSService.DanhMucData GetDanhMucByID(string maLoaiDanhMuc) {
            return base.Channel.GetDanhMucByID(maLoaiDanhMuc);
        }
        
        public System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucData> GetDanhMucByCriteria(string whereCondition) {
            return base.Channel.GetDanhMucByCriteria(whereCondition);
        }
        
        public System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucData> GetDanhMucBySizeCriteria(int size, string whereCondition) {
            return base.Channel.GetDanhMucBySizeCriteria(size, whereCondition);
        }
        
        public int GetDanhMucCount(string whereCondition) {
            return base.Channel.GetDanhMucCount(whereCondition);
        }
        
        public System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucData> GetDanhMucPaging(string whereCondition, int pageSize, int currentPage, string sortByColumns) {
            return base.Channel.GetDanhMucPaging(whereCondition, pageSize, currentPage, sortByColumns);
        }
        
        public int AddDanhMucItem(HS.Service.Connection.HSService.DanhMucItemData data) {
            return base.Channel.AddDanhMucItem(data);
        }
        
        public int ChangeDanhMucItem(HS.Service.Connection.HSService.DanhMucItemData data) {
            return base.Channel.ChangeDanhMucItem(data);
        }
        
        public int RemoveDanhMucItem(HS.Service.Connection.HSService.DanhMucItemData data) {
            return base.Channel.RemoveDanhMucItem(data);
        }
        
        public System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucItemData> GetDanhMucItemsByDanhMuc(string maLoaiDanhMuc) {
            return base.Channel.GetDanhMucItemsByDanhMuc(maLoaiDanhMuc);
        }
        
        public System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucItemData> GetDanhMucItems() {
            return base.Channel.GetDanhMucItems();
        }
        
        public HS.Service.Connection.HSService.DanhMucItemData GetDanhMucItemByID(System.Guid iD) {
            return base.Channel.GetDanhMucItemByID(iD);
        }
        
        public System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucItemData> GetDanhMucItemByCriteria(string whereCondition) {
            return base.Channel.GetDanhMucItemByCriteria(whereCondition);
        }
        
        public System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucItemData> GetDanhMucItemBySizeCriteria(int size, string whereCondition) {
            return base.Channel.GetDanhMucItemBySizeCriteria(size, whereCondition);
        }
        
        public int GetDanhMucItemCount(string whereCondition) {
            return base.Channel.GetDanhMucItemCount(whereCondition);
        }
        
        public System.Collections.Generic.List<HS.Service.Connection.HSService.DanhMucItemData> GetDanhMucItemPaging(string whereCondition, int pageSize, int currentPage, string sortByColumns) {
            return base.Channel.GetDanhMucItemPaging(whereCondition, pageSize, currentPage, sortByColumns);
        }
    }
}
